### PR TITLE
Fix some issues in rubygems 3.3.9

### PR DESCRIPTION
**Pull request by vmi**
I fixed rubygems-server 0.1.0 not working with rubygems 3.3.9.

**NOTE: This PR conflicts with #2.**

### CODE REVIEW

**Comment by djberg96** [comment]
Well, you could've suggested changes to my PR, but ok.

Does this PR address the port handling failure?

**Comment by djberg96** [comment]
Looks like it passes, so I'll go ahead and close mine.

**Comment by djberg96** [comment]
@deivid-rodriguez or @simi I don't know what the proper process is for merging any more, are you ok with this?

**Comment by simi** [comment]
Glad to see this fixed. If I remember well, this is not the first time this plugin get broken due to changes in RubyGems. Anyone any idea how to prevent this? Would it be enough to setup daily CI testing latest RubyGems HEAD and latest RubyGems release?

**Comment by deivid-rodriguez** [comment]
I think it is the first time, at least I see no further issues/PRs in the extracted repository. I think you might be remembering this issue being reported in Slack, but it's the same issue that never got fixed.

In any case, CI against RubyGems HEAD and latest version should help preventing this, yeah.

**Comment by simi** [comment]
@deivid-rodriguez https://github.com/rubygems/rubygems-server/pull/6

**Pull request merged**
